/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BinanceFuturesApiKeyConfig = IDL.Record({
  'binanceApiSecret' : IDL.Text,
  'binanceApiKey' : IDL.Text,
});
export const Tab = IDL.Variant({
  'alerts' : IDL.Null,
  'openInterest' : IDL.Null,
  'pairs' : IDL.Null,
  'statistics' : IDL.Null,
});
export const UserPreferences = IDL.Record({
  'selectedTab' : Tab,
  'favoritePairs' : IDL.Vec(IDL.Text),
  'alertThresholds' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addFavoritePair' : IDL.Func([IDL.Text], [], []),
  'get24hrTicker' : IDL.Func([], [IDL.Text], []),
  'getAllApiKeyConfigs' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, BinanceFuturesApiKeyConfig))],
      ['query'],
    ),
  'getAllUserPreferences' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserPreferences))],
      ['query'],
    ),
  'getKlines' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
  'getLongShortAccountRatio' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'getOpenInterest' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getUserFavoritePairs' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getUserPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
  'retrieveApiKeyConfig' : IDL.Func(
      [],
      [BinanceFuturesApiKeyConfig],
      ['query'],
    ),
  'saveApiKeyConfig' : IDL.Func([BinanceFuturesApiKeyConfig], [], []),
  'saveUserPreferences' : IDL.Func([UserPreferences], [], []),
  'setSelectedTab' : IDL.Func([Tab], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAlertThreshold' : IDL.Func([IDL.Text, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BinanceFuturesApiKeyConfig = IDL.Record({
    'binanceApiSecret' : IDL.Text,
    'binanceApiKey' : IDL.Text,
  });
  const Tab = IDL.Variant({
    'alerts' : IDL.Null,
    'openInterest' : IDL.Null,
    'pairs' : IDL.Null,
    'statistics' : IDL.Null,
  });
  const UserPreferences = IDL.Record({
    'selectedTab' : Tab,
    'favoritePairs' : IDL.Vec(IDL.Text),
    'alertThresholds' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addFavoritePair' : IDL.Func([IDL.Text], [], []),
    'get24hrTicker' : IDL.Func([], [IDL.Text], []),
    'getAllApiKeyConfigs' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, BinanceFuturesApiKeyConfig))],
        ['query'],
      ),
    'getAllUserPreferences' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserPreferences))],
        ['query'],
      ),
    'getKlines' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [IDL.Text], []),
    'getLongShortAccountRatio' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'getOpenInterest' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getUserFavoritePairs' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getUserPreferences' : IDL.Func([], [IDL.Opt(UserPreferences)], ['query']),
    'retrieveApiKeyConfig' : IDL.Func(
        [],
        [BinanceFuturesApiKeyConfig],
        ['query'],
      ),
    'saveApiKeyConfig' : IDL.Func([BinanceFuturesApiKeyConfig], [], []),
    'saveUserPreferences' : IDL.Func([UserPreferences], [], []),
    'setSelectedTab' : IDL.Func([Tab], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAlertThreshold' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };