/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BinanceFuturesApiKeyConfig {
  'binanceApiSecret' : string,
  'binanceApiKey' : string,
}
export type Tab = { 'alerts' : null } |
  { 'openInterest' : null } |
  { 'pairs' : null } |
  { 'statistics' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserPreferences {
  'selectedTab' : Tab,
  'favoritePairs' : Array<string>,
  'alertThresholds' : Array<[string, number]>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addFavoritePair' : ActorMethod<[string], undefined>,
  'get24hrTicker' : ActorMethod<[], string>,
  'getAllApiKeyConfigs' : ActorMethod<
    [],
    Array<[Principal, BinanceFuturesApiKeyConfig]>
  >,
  'getAllUserPreferences' : ActorMethod<
    [],
    Array<[Principal, UserPreferences]>
  >,
  'getKlines' : ActorMethod<[string, string, bigint], string>,
  'getLongShortAccountRatio' : ActorMethod<[string, string, bigint], string>,
  'getOpenInterest' : ActorMethod<[string], string>,
  'getUserFavoritePairs' : ActorMethod<[], Array<string>>,
  'getUserPreferences' : ActorMethod<[], [] | [UserPreferences]>,
  'retrieveApiKeyConfig' : ActorMethod<[], BinanceFuturesApiKeyConfig>,
  'saveApiKeyConfig' : ActorMethod<[BinanceFuturesApiKeyConfig], undefined>,
  'saveUserPreferences' : ActorMethod<[UserPreferences], undefined>,
  'setSelectedTab' : ActorMethod<[Tab], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAlertThreshold' : ActorMethod<[string, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];