/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserPreferences {
    selectedTab: Tab;
    favoritePairs: Array<string>;
    alertThresholds: Array<[string, number]>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface BinanceFuturesApiKeyConfig {
    binanceApiSecret: string;
    binanceApiKey: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum Tab {
    alerts = "alerts",
    openInterest = "openInterest",
    pairs = "pairs",
    statistics = "statistics"
}
export interface backendInterface {
    addFavoritePair(pair: string): Promise<void>;
    get24hrTicker(): Promise<string>;
    getAllApiKeyConfigs(): Promise<Array<[Principal, BinanceFuturesApiKeyConfig]>>;
    getAllUserPreferences(): Promise<Array<[Principal, UserPreferences]>>;
    getKlines(symbol: string, interval: string, limit: bigint): Promise<string>;
    getLongShortAccountRatio(symbol: string, period: string, limit: bigint): Promise<string>;
    getOpenInterest(symbol: string): Promise<string>;
    getUserFavoritePairs(): Promise<Array<string>>;
    getUserPreferences(): Promise<UserPreferences | null>;
    retrieveApiKeyConfig(): Promise<BinanceFuturesApiKeyConfig>;
    saveApiKeyConfig(config: BinanceFuturesApiKeyConfig): Promise<void>;
    saveUserPreferences(preferences: UserPreferences): Promise<void>;
    setSelectedTab(tab: Tab): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAlertThreshold(symbol: string, threshold: number): Promise<void>;
}
import type { Tab as _Tab, UserPreferences as _UserPreferences } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addFavoritePair(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavoritePair(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavoritePair(arg0);
            return result;
        }
    }
    async get24hrTicker(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.get24hrTicker();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get24hrTicker();
            return result;
        }
    }
    async getAllApiKeyConfigs(): Promise<Array<[Principal, BinanceFuturesApiKeyConfig]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApiKeyConfigs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApiKeyConfigs();
            return result;
        }
    }
    async getAllUserPreferences(): Promise<Array<[Principal, UserPreferences]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserPreferences();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserPreferences();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getKlines(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getKlines(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKlines(arg0, arg1, arg2);
            return result;
        }
    }
    async getLongShortAccountRatio(arg0: string, arg1: string, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLongShortAccountRatio(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLongShortAccountRatio(arg0, arg1, arg2);
            return result;
        }
    }
    async getOpenInterest(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenInterest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenInterest(arg0);
            return result;
        }
    }
    async getUserFavoritePairs(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserFavoritePairs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserFavoritePairs();
            return result;
        }
    }
    async getUserPreferences(): Promise<UserPreferences | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPreferences();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPreferences();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async retrieveApiKeyConfig(): Promise<BinanceFuturesApiKeyConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.retrieveApiKeyConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retrieveApiKeyConfig();
            return result;
        }
    }
    async saveApiKeyConfig(arg0: BinanceFuturesApiKeyConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveApiKeyConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveApiKeyConfig(arg0);
            return result;
        }
    }
    async saveUserPreferences(arg0: UserPreferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserPreferences(to_candid_UserPreferences_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserPreferences(to_candid_UserPreferences_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setSelectedTab(arg0: Tab): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSelectedTab(to_candid_Tab_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSelectedTab(to_candid_Tab_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAlertThreshold(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlertThreshold(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlertThreshold(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Tab_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tab): Tab {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPreferences]): UserPreferences | null {
    return value.length === 0 ? null : from_candid_UserPreferences_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    selectedTab: _Tab;
    favoritePairs: Array<string>;
    alertThresholds: Array<[string, number]>;
}): {
    selectedTab: Tab;
    favoritePairs: Array<string>;
    alertThresholds: Array<[string, number]>;
} {
    return {
        selectedTab: from_candid_Tab_n5(_uploadFile, _downloadFile, value.selectedTab),
        favoritePairs: value.favoritePairs,
        alertThresholds: value.alertThresholds
    };
}
function from_candid_tuple_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserPreferences]): [Principal, UserPreferences] {
    return [
        value[0],
        from_candid_UserPreferences_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alerts: null;
} | {
    openInterest: null;
} | {
    pairs: null;
} | {
    statistics: null;
}): Tab {
    return "alerts" in value ? Tab.alerts : "openInterest" in value ? Tab.openInterest : "pairs" in value ? Tab.pairs : "statistics" in value ? Tab.statistics : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserPreferences]>): Array<[Principal, UserPreferences]> {
    return value.map((x)=>from_candid_tuple_n2(_uploadFile, _downloadFile, x));
}
function to_candid_Tab_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tab): _Tab {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserPreferences_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPreferences): _UserPreferences {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    selectedTab: Tab;
    favoritePairs: Array<string>;
    alertThresholds: Array<[string, number]>;
}): {
    selectedTab: _Tab;
    favoritePairs: Array<string>;
    alertThresholds: Array<[string, number]>;
} {
    return {
        selectedTab: to_candid_Tab_n10(_uploadFile, _downloadFile, value.selectedTab),
        favoritePairs: value.favoritePairs,
        alertThresholds: value.alertThresholds
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tab): {
    alerts: null;
} | {
    openInterest: null;
} | {
    pairs: null;
} | {
    statistics: null;
} {
    return value == Tab.alerts ? {
        alerts: null
    } : value == Tab.openInterest ? {
        openInterest: null
    } : value == Tab.pairs ? {
        pairs: null
    } : value == Tab.statistics ? {
        statistics: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
